Updates Extools to 515 - 1609
yogstation13/extools pull request #19
Opened 2023-05-07 15:25 UTC by JamieD1

2023-05-07 16:22 UTC, Moja10 commented
I don't like it, please close?

2023-05-07 16:23 UTC, Moja10 commented
Please convert all the hexadecimal to human readable decimal system thanks xoxo

2023-05-07 16:41 UTC, JamieD1 commented on byond-extools/src/core/find_functions.cpp
> +	FIND_OR_DIE(CallProcByName, "55 8B EC 81 EC 98 00 00 00 A1 ?? ?? ?? ?? 33 C5 89 45 FC 8B 55");
Should be seperated

2023-05-07 16:43 UTC, JamieD1 commented on byond-extools/src/core/find_functions.cpp
> +	FIND_OR_DIE(SendMaps, "55 8B EC 6A FF 68 C7 B0 31 10 64 A1 00 00 00 00 50 81 EC 58 07 00 00 A1 90 B3 38 10 33 C5 89 45 F0 53 56 57 50 8D 45 F4 64 A3 00 00 00 00 A0 98");
here too

2023-05-07 16:44 UTC, JamieD1 commented on byond-extools/src/core/find_functions.cpp
>  	FIND_OR_DIE(StartTiming, "55 8B EC 56 8B 75 ?? 56 80 4E ?? ??");
this needs doing too

2023-05-07 16:56 UTC, JamieD1 commented on byond-extools/src/core/find_functions.cpp
> +	FIND_OR_DIE(DelDatum, "55 8b ec 8b 4d 08 3b 0d ?? ?? ?? ?? 73 55 a1 ?? ?? ?? ?? 8b 04 88 85 c0 74 49 8b 50 10 81 fa 00 00 00 70");
double deldatum

2023-05-07 17:00 UTC, JamieD1 commented on byond-extools/src/core/find_functions.cpp
> +	current_execution_context_ptr = *(ExecutionContext * **)Pocket::Sigscan::FindPattern(BYONDCORE, "A1 ?? ?? ?? ?? FF 75 ?? 89 4D ?? 8B 4D ?? 8B 00 6A 00 52 6A 12 FF 70 ??", 1);
Adam says this will break shit

2023-05-08 10:37 UTC, JamieD1 commented on byond-extools/src/core/find_functions.cpp
> +	FIND_OR_DIE(CallProcByName, "55 8B EC 81 EC 98 00 00 00 A1 ?? ?? ?? ?? 33 C5 89 45 FC 8B 55");
Was wrong before.

2023-05-08 21:11 UTC, adamsong requested changes
On windows
514: Hard crash, no log
515: Incorrect mappings for DestroyDatum, and SendMaps

2023-05-11 18:55 UTC, closed without merging